# Generated by packaging/homebrew/render-cask.sh in mkv-track-editor's CI.
# Manual edits are overwritten on the next release.
cask "mkv-track-editor" do
  version "0.1.1"
  sha256 "5479a05cc66a53d6ed231e972a1bdf94822c03bddc18341d95eea02804ee1503"

  url "https://github.com/bugsbunny-25/homebrew-tap/releases/download/mkv-track-editor-v0.1.1/mkv-track-editor-#{version}-macos-arm64.tar.gz"
  name "MKV Track Editor"
  desc "Edit MKV tracks with profiles and Radarr/Sonarr-compatible naming"
  homepage "https://github.com/bugsbunny-25/homebrew-tap"

  # The app shells out to mkvmerge/mkvpropedit and mediainfo for every
  # analysis and edit.
  depends_on arch: :arm64
  depends_on formula: "media-info"
  depends_on formula: "mkvtoolnix"
  depends_on :macos

  app "mkv-track-editor-#{version}-macos-arm64/MKV Track Editor.app"
  binary "#{appdir}/MKV Track Editor.app/Contents/MacOS/mkv-track-editor"

  zap trash: "~/Library/Application Support/mkv-track-editor"

  caveats <<~CAVEATS
    MKV Track Editor is not notarized by Apple, so macOS blocks its first
    launch after each install or upgrade. Open it once, then choose
    "Open Anyway" in System Settings > Privacy & Security. That also allows
    the mkv-track-editor command, which is the same program.
  CAVEATS
end
