# Generated by packaging/homebrew/render-formula.sh in mkv-track-editor's CI.
# Manual edits are overwritten on the next release.
class MkvTrackEditor < Formula
  desc "Edit MKV tracks with profiles and Radarr/Sonarr-compatible naming"
  homepage "https://github.com/bugsbunny-25/homebrew-tap"
  version "0.1.1"
  license "MIT"

  # Linked: fontconfig. Loaded at runtime: D-Bus (the file dialogs talk to
  # xdg-desktop-portal through it) and the windowing/GL stack: X11/XCB,
  # xkbcommon, Wayland and EGL/GL (Mesa). mkvtoolnix and media-info: the app
  # shells out to mkvmerge/mkvpropedit and mediainfo for every analysis and
  # edit. On macOS the cask installs the app instead:
  #   brew install --cask mkv-track-editor
  depends_on "dbus"
  depends_on "fontconfig"
  depends_on "libx11"
  depends_on "libxcb"
  depends_on "libxcursor"
  depends_on "libxi"
  depends_on "libxkbcommon"
  depends_on "libxrender"
  depends_on :linux
  depends_on "media-info"
  depends_on "mesa"
  depends_on "mkvtoolnix"
  depends_on "wayland"

  on_linux do
    on_intel do
      url "https://github.com/bugsbunny-25/homebrew-tap/releases/download/mkv-track-editor-v0.1.1/mkv-track-editor-0.1.1-linux-x86_64.tar.gz"
      sha256 "705eb6bde4ceadbb2f6cf25d2d3f6c3c352016850bbcc751523d52e001839729"
    end
    on_arm do
      url "https://github.com/bugsbunny-25/homebrew-tap/releases/download/mkv-track-editor-v0.1.1/mkv-track-editor-0.1.1-linux-arm64.tar.gz"
      sha256 "78f39cfcfd57bcf8d4b67f67247f89fd028b93b5bebfbbfd03e71e7f6809298f"
    end
  end

  def install
    bin.install "mkv-track-editor"
    # The archive is built against the system glibc; point it at Homebrew's
    # loader and libraries (as bottles are) so the dependencies above are the
    # ones it loads.
    ld_so = HOMEBREW_PREFIX/"lib/ld.so"
    (bin/"mkv-track-editor").patch!(
      interpreter: (ld_so.to_s if ld_so.readable?),
      rpath:       (HOMEBREW_PREFIX/"lib").to_s,
    )
  end

  test do
    assert_path_exists bin/"mkv-track-editor"
    system formula_opt_bin("mkvtoolnix")/"mkvmerge", "--version"
    system formula_opt_bin("media-info")/"mediainfo", "--version"
  end
end
